version: '2'

services:
  web:
    environment:
      NODE_ENV: development
    image: awsgoodness/web-dev
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/web
    command: yarn start
    
  api:
    image: awsgoodness/api-dev
    environment: 
      NODE_ENV: development
    ports:
      - 3002:3000
    volumes: 
      - $API_ROOT:/usr/src/api
    command: nodemon .

  mysqlDb:
    image: awsgoodness/mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PWD}"
    ports:
      - 3306:3306
    volumes:
      - ../dev-db:/var/lib/mysql